name: build
on: [push]

jobs:
  build:
    name: Loopringj build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build (non-master branch)
        if: github.ref != 'refs/heads/main'
        run: ./gradlew build
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
##        if: failure()
      - name: New release (including build and pushing artifacts)
        if: github.ref == 'refs/heads/main'
        run: ./gradlew release
      - name: Upload all reports in case of error
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: build-reports
          path: "*/build/reports"